stages:
  - lint
  - docs
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e . --find-links https://download.pytorch.org/whl/torch_stable.html

pre-commit_py3.10:
  stage: lint
  image: python:3.10.13
  script:
    - pre-commit run --all-files
  allow_failure: true

pre-commit_py3.11:
  stage: lint
  image: python:3.11.7
  script:
    - pre-commit run --all-files
  allow_failure: true

sphinx_py3.10:
  stage: docs
  image: python:3.10.13
  script:
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/_build/html
  allow_failure: true

sphinx_py3.11:
  stage: docs
  image: python:3.11.7
  script:
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/_build/html
  allow_failure: true

pages:
  stage: deploy
  script:
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
