stages:
  - lint
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e . --find-links https://download.pytorch.org/whl/torch_stable.html
  - cd venv/Scripts
  - ls

pre-commit_py3.10:
  stage: lint
  image: python:3.10.13
  script:
    - pre-commit run --all-files
  allow_failure: true

pre-commit_py3.11:
  stage: lint
  image: python:3.11.7-windowsservercore-1809
  script:
    - pre-commit run --all-files
  allow_failure: true

sphinx_py3.10:
  stage: deploy
  image: python:3.10.13
  script:
    - cd docs
    - make html
  allow_failure: true

pages:  # Run Sphinx with Python 3.11
  stage: deploy
  image: python:3.11.7
  script:
    - cd docs
    - make html
    - mv _build/html ../public
  artifacts:
    paths:
      - public
  allow_failure: true
