exclude: ^(docs/|external/|venv/|tests/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args: [--disallow-any-generics, --disallow-untyped-defs, --disable-error-code=import-untyped]
        language: system
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.6
    hooks:
      - id: gitlab-ci-linter
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.15
    hooks:
      - id: pymarkdown
        args:
          - -d
          - md013
          - scan
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=175]
  - repo: https://github.com/jshwi/docsig
    rev: v0.44.2
    hooks:
      - id: docsig
        args:
          - "--check-class"
          - "--check-dunders"
          - "--check-overridden"
          - "--check-protected"
          - "--summary"
