defaults:
  - pipeline/default@_here_
  - _self_

feature_pipeline:
  processed_path: data/processed
  transformation_pipeline:
    transformations: []
  column_pipeline:
    columns: []

target_pipeline:

model_loop_pipeline:
  pretrain_pipeline:
    pretrain_steps: []

  model_blocks_pipeline:
    model_blocks:

      # Pytorch model
      - _target_: src.pipeline.model.model_loop.model_blocks.torch_block.TorchBlock
        model:
          _target_: torch.nn.Conv2d
          in_channels: 8
          out_channels: 1
          kernel_size: 3
          padding: 1

        optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
          _target_: functools.partial
          _args_:
            - _target_: hydra.utils.get_class
              path: torch.optim.Adam
          lr: 0.001
        scheduler:
          _target_: functools.partial
          _args_:
            - _target_: hydra.utils.get_class
              path: torch.optim.lr_scheduler.CosineAnnealingLR
          T_max: 30
        criterion:
          _target_: src.modules.loss.dice_loss.DiceLoss
        epochs: 30
        batch_size: 32
        patience: 10
        layerwise_lr_decay: 0.9

# Post processing pipeline
post_processing_pipeline:
