_target_: src.pipeline.model.model.ModelPipeline

feature_pipeline:
  _target_: src.pipeline.model.feature.feature.FeaturePipeline

  transformation_pipeline:
    _target_: src.pipeline.model.feature.transformation.transformation.TransformationPipeline

  column_pipeline:
    _target_: src.pipeline.model.feature.column.column.ColumnPipeline

target_pipeline: None

model_loop_pipeline:
  _target_: src.pipeline.model.model_loop.model_loop.ModelLoopPipeline

post_processing_pipeline:
  _target_: src.pipeline.model.post_processing.post_processing.PostProcessingPipeline
