defaults:

  - /model/convNextf18@models.convNextf18
  - /model/vgg13-unet-bs16-f18-e100-fdb@models.vgg13-unet-bs16-f18-e100-fdb
  - /model/swin-unetr-f18-fdb@models.swin-unetr-f18-fdb
  - /model/vgg13-unet-bs16-f18-e75-fdb2@models.vgg13-unet-bs16-f18-e75-fdb2
  - /model/res2net50-unet-bs16-f13-e100-fdb@models.res2net50-unet-bs16-f13-e100-fdb
  - /model/swin-unetr-f13-fdb@models.swin-unetr-f13-fdb
  

_target_: src.pipeline.ensemble.weighted_ensemble.WeightedEnsemble
_convert_: 'partial'

weights:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0

post_ensemble_steps:
  - _target_: src.pipeline.model.post_processing.threshold.Threshold
    threshold: 0.5