defaults:
  - /model/vgg13-linknet-bs16-f18-e75@vgg13-linknet-bs16-f18-e75
  - /model/vgg13-unet-bs24-f18-e75@vgg13-unet-bs24-f18-e75
  - /model/vgg13-unet-bs24-f18-e75-0sigma@vgg13-unet-bs24-f18-e75-0sigma

_target_: src.pipeline.ensemble.weighted_ensemble.WeightedEnsemble
_convert_: 'partial'

weights:
  - 1
  - 1
  - 1



post_ensemble_steps:
  - _target_: src.pipeline.model.post_processing.threshold.Threshold
    threshold: 0.5