defaults:
  - /model/vgg13-unet-bs16-f18-e75@models.vgg13-unet-bs16-f18-e75
  - /model/swin-unetr-f18@models.swin-unetr-f18
  - /model/vgg19-unet-bs16-f18-e75@models.vgg19-unet-bs16-f18-e75
  - /model/vgg11-unet-bs32-f18-e75@models.vgg11-unet-bs32-f18-e75



_target_: src.pipeline.ensemble.weighted_ensemble.WeightedEnsemble
_convert_: 'partial'

weights:
  - 1
  - 1
  - 1
  - 1


post_ensemble_steps:
  - _target_: src.pipeline.model.post_processing.threshold.Threshold
    threshold: 0.5