defaults:
  - /model/horsemen/horsemen1@models.horsemen1
  - /model/horsemen/horsemen3@models.horsemen3

_target_: src.pipeline.ensemble.weighted_ensemble.WeightedEnsemble
_convert_: 'partial'

weights:
  - 0.5
  - 0.5
post_ensemble_steps:
