defaults:
  - /model/hugo@models.hugo
  - /model/FUnet-v3@models.FUnet-v3

_target_: src.pipeline.ensemble.logical_ensemble.LogicalEnsemble
_convert_: 'partial'

ensemble_type: union

post_ensemble_steps:
