defaults:
  - /model/emiel@models.emiel
  - /model/hugo@models.hugo

_target_: src.pipeline.ensemble.weighted_ensemble.WeightedEnsemble
_convert_: 'partial'

weights:
  - 0.5
  - 0.5
post_ensemble_steps:
  - _target_: src.pipeline.model.post_processing.threshold.Threshold
