defaults:
  - /model/vgg13-unet-bs16-f13-e75@models.vgg13-unet-bs16-f13-e75
  - /model/swin-unetr@models.swin-unetr
  - /model/vgg19-unet-bs16-f13-e75@models.vgg19-unet-bs16-f13-e75
  - /model/vgg11-unet-bs32-f10-e75@models.vgg11-unet-bs32-f10-e75
  - /model/vgg13-linknet-bs16-f13-e75@models.vgg13-linknet-bs16-f13-e75
  - /model/vgg13-unet-bs24-f13-e75@models.vgg13-unet-bs24-f13-e75
  - /model/vgg16-unet-bs24-f13-e75-0sigma@models.vgg16-unet-bs24-f13-e75-0sigma


_target_: src.pipeline.ensemble.weighted_ensemble.WeightedEnsemble
_convert_: 'partial'

weights:
  - 0.125
  - 0.250
  - 0.125
  - 0.125
  - 0.125
  - 0.125
  - 0.125


post_ensemble_steps:
  - _target_: src.pipeline.model.post_processing.threshold.Threshold
    threshold: 0.9
