defaults:
  - /model/conv2d@models.conv2d1
  - /model/conv2d@models.conv2d2

_target_: src.pipeline.ensemble.weighted_ensemble.WeightedEnsemble
_convert_: 'partial'

weights:
  - 0.5
  - 0.5
post_ensemble_steps:
